name: Java CI with Gradle

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Run Tests
      run: ./gradlew clean test
    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html